service: weathergpsiot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: iamadmin
  stage: dev
  # all actions on this bucket and objects: weather-gps-iot-nickyiliwang
  iam:
      role:
        statements:
          - Effect: 'Allow'
            Action:
              - '*'
            Resource: arn:aws:s3:::weather-gps-iot-nickyiliwang
          - Effect: 'Allow'
            Action:
              - '*'
            Resource: arn:aws:s3:::weather-gps-iot-nickyiliwang/*

functions:
  weatherGPSIoT:
    handler: lambda/weatherGPSIoTLambda.handler
  extractTransformCSVToJSON:
    handler: lambda/extractTransformCSVToJSON.handler
  weatherGPSIoTWeb:
    handler: index.handler
    events:
      - http:
          method: POST
          path: /
          cors: true
  rip:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /fuck
          cors: true