service: weathergpsiot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: iamadmin
  stage: dev
  iam:
      role:
        statements:
          - Effect: 'Allow'
            Action:
              - 's3:ListBucket'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: ServerlessDeploymentBucket
          - Effect: 'Allow'
            Action:
              - 's3:PutObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: ServerlessDeploymentBucket
                  - '/*'

functions:
  weatherGPSIoT:
    handler: /lambda/weatherGPSIoTLambda.weatherGPSIoT.
  extractTransformCSVToJSON:
    handler: /lambda/weatherGPSIoTLambda.weatherGPSIoT.
  weatherGPSIoTWeb:
    handler: index.handler
    events:
      - http:
          method: POST
          path: /
          cors: true
  rip:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /fuck
          cors: true